apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: otus-hw8
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      automountServiceAccountToken: false
      containers:
        - name: auth
          image: shacoss/auth-service:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
              name: auth-port
          envFrom:
            - configMapRef:
                name: db-settings
            - configMapRef:
                name: rabbitmq-settings
            - secretRef:
                name: db-secret
            - secretRef:
                name: rabbitmq-secret
          env:
            - name: SERVER_PORT
              value: ":8080"

