apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: otus-hw10
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      automountServiceAccountToken: false
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:1.28
          command:
            - "sh"
            - "-c"
            - "until nc -z rabbitmq 5672; do echo 'Waiting for RabbitMQ...'; sleep 5; done"
        - name: wait-for-postgres
          image: busybox:1.28
          command:
            - "sh"
            - "-c"
            - "until nc -z postgres-postgresql 5432; do echo 'Waiting for PostgreSQL...'; sleep 5; done"
      containers:
        - name: billing
          image: shacoss/billing-service:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
              name: billing-port
          envFrom:
            - configMapRef:
                name: db-settings
            - configMapRef:
                name: rabbitmq-settings
            - secretRef:
                name: db-secret
            - secretRef:
                name: rabbitmq-secret
          env:
            - name: SERVER_PORT
              value: ":8080"
