apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-crud-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: user-crud-sv
                port:
                  number: 80