apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: health-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /health
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /otusapp/([A-Za-z]+)/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: health-service-sv
                port:
                 number: 80
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: health-service-sv
                port:
                  number: 80