apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
data:
  init.sql: |
    create table if not exists public.user(
        id serial primary key,
        name character varying,
        email character varying
    );